from __future__ import annotations

import json
from typing import Any

from packages.model_gateway.base import BaseModelClient


class MockModelClient(BaseModelClient):
    provider = "mock"
    model = "mock-repomind"

    async def generate_text(self, messages: list[dict[str, Any]]) -> str:
        prompt = "\n".join(str(message.get("content", "")) for message in messages)
        if "question" in prompt.lower():
            return "I found the answer in the repository evidence. See the attached citations."
        return "RepoMind mock response generated from repository evidence."

    async def generate_json(self, messages: list[dict[str, Any]], schema: dict[str, Any]) -> dict[str, Any]:
        title = _infer_title(messages)
        return {
            "title": title,
            "summary": f"{title} generated from repository evidence.",
            "sections": [
                {
                    "heading": "Evidence-backed summary",
                    "content": "This page is generated by the MockModelClient so the MVP can run without API keys.",
                    "citations": [],
                }
            ],
            "diagrams": [],
            "related_pages": [],
        }


def _infer_title(messages: list[dict[str, Any]]) -> str:
    text = "\n".join(str(message.get("content", "")) for message in messages)
    for marker in ("title:", "page:"):
        lowered = text.lower()
        index = lowered.find(marker)
        if index >= 0:
            value = text[index + len(marker):].splitlines()[0].strip()
            if value:
                return value
    try:
        payload = json.loads(text)
        if isinstance(payload, dict) and payload.get("title"):
            return str(payload["title"])
    except json.JSONDecodeError:
        pass
    return "RepoMind Page"
